repos:
  - repo: https://github.com/igorshubovych/markdownlint-cli2
    rev: v0.20.0
    hooks:
      - id: markdownlint-cli2
        args: ["--config", ".markdownlint-cli2.yaml"]
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.1
    hooks:
      - id: yamllint
        args: ["-c", ".yamllint"]
